### ISSUE TITLE
Liquefier's output is not worth the input at all.  (plus "trimming" request)

### ISSUE THREAD

**Issue by Redoneter593** [genNAowl/Upgraded-Factories#10]
Currently, the Liquefier uses 20 scrap, and to make 70 slag. This is 20x the Melter's (vanilla version) input, and yet it only has 6x the output, AND adds in pyratite as a requirement. As a result it's waste large of the scrap used compared to vanilla as well as other mods that have a building with double to triple the scrap & slag input/output and are actually efficient. 

In order to make Liquefier actually worth using, I'm suggesting one of the following changes be implemented: 

A) scrap requirement decreased to 6-8, and removing the pyratite requirement
B) idea A, but production time increased to 2 seconds and the Pyratite is an optional booster that doubles production speed 
C) scrap requirement decreased to 12-14 and production time increased to 2 seconds 
D) idea B, but the Pyratite is an optional booster that doubles production speed 

And on another note, while I really quite like the Furnace, Spore Compactor, Crusher, Coal Synthesizer, Nurturer, and Water/Oil Extorters, I do not care for the other buildings (due to the extra type of resource required) and it would be greatly appreciated if there was a version without the other buildings (the ones I didn't list) as they result in a quite a bit of extra clutter to the build menu. The reason I am asking here on github for such is because I've already invested quite a few hours of my own time (with assistance from the modding channel from the mindustry discord no less), but failed to yield any results (the mod simply doesn't appear in the list of installed mods), and I am honestly low on sanity at this point trying to do such on my end.

**Comment by genNAowl** [comment]
The Liquefier uses 20 scrap and has a craft time of 1 second. This means it uses 20 scrap/sec to make 70 slag/sec (Just as you said)

However, the difference here is that the Melter uses 1 scrap and has a craft time of 0.16 seconds. This means it actually uses 6.25 scrap/sec to make 12 slag/sec. 

20 scrap for 70 slag or 6.25 scrap for 12 slag? The efficiency difference is huge. 

The thing is, this is an easy mistake to make because liquid values are standardized but item values are not; This is fixed in 7.0, but for now, remember to factor craft time into ration calculations. 

As for your request for a separate mod with certain content removed, a custom jar file with certain blocks removed can be found here: https://github.com/genNAowl/Upgraded-Factories/actions/runs/951096051
Click on that link, press the "dexed" under the large "Artifacts", extract all, then import the jar mod inside. 

*I do not plan on updating this "modified" version of the mod along with the main version*
